version: "3.0"
services:
  web:
    image: gcr.io/docker-swarm-281107/serialization-hard-1-polypharism:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      labels:
        - traefik.http.routers.serialization-hard-1-polypharism.rule=Host(`polypharism.mctf.online`)
        - traefik.http.services.serialization-hard-1-polypharism.loadbalancer.server.port=80
        - traefik.docker.network=traefik
    # networks:
    #   - traefik
    environment:
      flag: "mctf{better_than_w@r}"


# networks:
#   traefik:
#     external:
#       name: traefik

    # networks:
    #     - traefik


# networks:
#   traefik:
#     external:
#       name: traefik